name: CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker
      uses: docker/setup-buildx-action@v2

    - name: Build Docker image
      run: docker build -t my-image-name .

    - name: Test Docker image
      run: |
        docker run my-image-name echo "Tests passed!"

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Deploy to Kubernetes
      run: |
        echo "Add your kubectl deployment steps here"
